# ============================================
# CAFM Backend - Development Profile
# Spring Boot 3.3.x with Java 23
# ============================================

spring:
  # JPA Development Settings
  jpa:
    hibernate:
      ddl-auto: none  # Disable validation temporarily - using Flyway for schema management
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        
  # DevTools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
  
  # JMX Configuration - Prevent MBean conflicts
  jmx:
    enabled: false  # Disable JMX to prevent MBean registration conflicts
      
# Server Configuration for Development
server:
  error:
    include-stacktrace: always
    include-exception: true
    
# Actuator - More endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  # Disable Zipkin tracing in development if Zipkin is not running
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      enabled: false  # Set to true if you have Zipkin running
      
# Logging - More verbose for development
logging:
  level:
    root: INFO
    com.cafm: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG
    org.flywaydb: DEBUG
    
# Application Development Settings
app:
  # Disable rate limiting in development
  api:
    rate-limit:
      enabled: false
      
  # CORS - Allow all origins in development
  security:
    cors:
      allowed-origins: "*"
      
# OpenAPI/Swagger - Enhanced for development
springdoc:
  swagger-ui:
    display-operation-id: true
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true
    show-common-extensions: true
    
# Development-specific properties
debug: false  # Set to true for Spring Boot debug mode