{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cafm-backend.fullname" . }}
  labels:
    {{- include "cafm-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cafm-backend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
  {{- else }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS outbound
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow database connections
  - to: []
    ports:
    - protocol: TCP
      port: 5432
  # Allow Redis connections
  - to: []
    ports:
    - protocol: TCP
      port: 6379
  {{- end }}
{{- end }}