apiVersion: v1
kind: Namespace
metadata:
  name: cafm-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cafm-config
  namespace: cafm-production
data:
  application.properties: |
    # Simple configuration for local testing
    server.port=8080
    spring.application.name=cafm-backend
    
    # Health checks
    management.endpoints.web.exposure.include=health,info,prometheus,metrics
    management.endpoint.health.show-details=always
    
    # Logging
    logging.level.root=INFO
    logging.level.com.cafm=DEBUG
    
    # Disable database for now
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.h2.console.enabled=true
    
    # Disable Flyway
    spring.flyway.enabled=false
    
    # Disable Redis for now
    spring.data.redis.port=0
    spring.cache.type=simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafm-backend
  namespace: cafm-production
  labels:
    app: cafm-backend
    version: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafm-backend
  template:
    metadata:
      labels:
        app: cafm-backend
        version: local
    spec:
      containers:
      - name: cafm-backend
        image: cafm-backend:java21-v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: "file:/app/config/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: cafm-config
---
apiVersion: v1
kind: Service
metadata:
  name: cafm-backend-service
  namespace: cafm-production
  labels:
    app: cafm-backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30005
    name: http
  selector:
    app: cafm-backend