spring:
  application:
    name: cafm-backend-test
    
  # Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  
  # JPA Configuration for Testing
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  # Disable Flyway for tests
  flyway:
    enabled: false
  
  # Redis Configuration (if needed, can use embedded)
  data:
    redis:
      host: localhost
      port: 6379
      
  # Security Configuration
  security:
    user:
      name: admin
      password: admin
  
  # Mail Configuration (disabled for tests)
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  
  # Actuator
  management:
    endpoints:
      web:
        exposure:
          include: health,info
          
  # WebSocket Configuration
  websocket:
    enabled: false

# JWT Configuration for Testing
jwt:
  secret: ThisIsAVeryLongSecretKeyForTestingPurposesOnlyAndShouldBeAtLeast256BitsLong123456789
  expiration: 3600000 # 1 hour
  refresh-expiration: 86400000 # 24 hours

# Security Configuration
security:
  login:
    max-attempts: 5
    lockout-duration-minutes: 30
    attempt-window-minutes: 15
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# File Storage Configuration (MinIO disabled for tests)
minio:
  enabled: false
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: cafm-test

# Cloudinary Configuration (disabled for tests)
cloudinary:
  enabled: false
  cloud-name: test
  api-key: test
  api-secret: test

# Logging Configuration
logging:
  level:
    root: WARN
    com.cafm.cafmbackend: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

# API Documentation (disabled for tests)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Test-specific properties
test:
  integration:
    enabled: true
  mock:
    external-services: true