name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  JAVA_VERSION: '23'

jobs:
  check-dependencies:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'oracle'
          cache: 'maven'

      - name: Check for Maven dependency updates
        run: |
          mvn versions:display-dependency-updates \
              versions:display-plugin-updates \
              versions:display-property-updates \
              -DprocessAllModules=true \
              -DgenerateBackupPoms=false \
              > dependency-report.txt

      - name: Check for security vulnerabilities
        run: |
          mvn org.owasp:dependency-check-maven:check \
              -Dformat=HTML \
              -DsuppressionFiles=dependency-check-suppressions.xml \
              || true

      - name: Parse dependency updates
        id: parse-updates
        run: |
          if grep -q "The following dependencies in Dependencies have newer versions" dependency-report.txt; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
            
            # Extract update summary
            echo "## Dependency Updates Available" > update-summary.md
            echo "" >> update-summary.md
            sed -n '/The following dependencies/,/^$/p' dependency-report.txt >> update-summary.md
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
            echo "No dependency updates available" > update-summary.md
          fi

      - name: Create pull request for updates
        if: steps.parse-updates.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '[Auto] Dependency Updates Available'
          body-path: update-summary.md
          branch: auto-dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: ${{ github.repository_owner }}

      - name: Upload dependency check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
          retention-days: 30

      - name: Notify about vulnerabilities
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: 'danger'
          text: 'Security vulnerabilities found in dependencies!'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true